### ISSUE TITLE
部署sandbox报错

### ISSUE THREAD

**Issue by luoMonkeyKing** [Winson-030/dify-kubernetes#30]
1.0.0版本，通过deployment部署sandbox时，报如下错误，并没有配置这个日志文件：
```
panic: open ./logs/2025-03-11.log: permission denied
goroutine 1 [running]:
github.com/langgenius/dify-sandbox/internal/utils/log.initlog(...)
/home/runner/work/dify-sandbox/dify-sandbox/internal/utils/log/core.go:158
github.com/langgenius/dify-sandbox/internal/utils/log.init.0()
/home/runner/work/dify-sandbox/dify-sandbox/internal/utils/log/core.go:151 +0x65
```

**Comment by Winson-030** [comment]
Permission denied. I think you should check volume permission

**Comment by luoMonkeyKing** [comment]
The dify-version-100 branch does not include volume configuration in the deployment.：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-sandbox
  namespace: dify
  labels:
    app: dify-sandbox
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dify-sandbox
  template:
    metadata:
      labels:
        app: dify-sandbox
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: dify-sandbox
        image: langgenius/dify-sandbox:0.2.10
        env:
        - name: API_KEY
          value: "dify-sandbox"
        - name: GIN_MODE
          value: "release"
        - name: WORKER_TIMEOUT
          value: "15"
        - name: ENABLE_NETWORK
          value: "true"
        - name: SANDBOX_PORT
          value: "8194"
          # uncomment if you want to use proxy
        - name: HTTP_PROXY
          value: 'http://dify-ssrf:3128'
        - name: HTTPS_PROXY
          value: 'http://dify-ssrf:3128'
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - "curl"
            - "-f"
            - "http://localhost:8194/health"
        ports:
        - containerPort: 8194
        imagePullPolicy: IfNotPresent
```

**Comment by luoMonkeyKing** [comment]
I also encountered a permission issue when deploying dify-ssrf：
```
cp: cannot create regular file '/docker-entrypoint.sh': Permission denied
```

**Comment by luoMonkeyKing** [comment]
> Permission denied. I think you should check volume permission

Even after I added the volume, I still get the same error.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-sandbox
  namespace: dify
  labels:
    app: dify-sandbox
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dify-sandbox
  template:
    metadata:
      labels:
        app: dify-sandbox
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-sandbox
        image: registry.ictnjpaas.com:8443/dify/langgenius/dify-sandbox:0.2.10
        env:
        - name: API_KEY
          value: "dify-sandbox"
        - name: GIN_MODE
          value: "release"
        - name: WORKER_TIMEOUT
          value: "15"
        - name: ENABLE_NETWORK
          value: "true"
        - name: SANDBOX_PORT
          value: "8194"
          # uncomment if you want to use proxy
        - name: HTTP_PROXY
          value: 'http://dify-ssrf:3128'
        - name: HTTPS_PROXY
          value: 'http://dify-ssrf:3128'
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - "curl"
            - "-f"
            - "http://localhost:8194/health"
        ports:
        - containerPort: 8194
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sandbox-dependencies
          mountPath: /dependencies
        - name: sandbox-conf
          mountPath: /conf
      volumes:
        - name: sandbox-dependencies
          persistentVolumeClaim:
            claimName: sandbox-dependencies
        - name: sandbox-conf
          persistentVolumeClaim:
            claimName: sandbox-conf
```
