### ISSUE TITLE
REDIS 环境变量占位符取值问题（Port could not be cast to integer value as '$(REDIS_PORT)'）

### ISSUE THREAD

**Issue by cainiao0131** [Winson-030/dify-kubernetes#44]
```
kubectl version
Client Version: v1.30.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5
```
```
git clone https://github.com/Winson-030/dify-kubernetes.git
kubectl apply -f dify-deployment.yaml
```
现象：
dify-deployment.yaml 中，CELERY_BROKER_URL 通过 $(REDIS_PORT) 取 REDIS_PORT 的值无法成功
调用接口：/workspaces/current/members/invite-email 返回：
```
{
    "result": "success",
    "invitation_results": [
        {
            "status": "failed",
            "email": "xxx@xx.com",
            "message": "Port could not be cast to integer value as '$(REDIS_PORT)'"
        }
    ]
}
```
```
# Dify Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-shared-config
  namespace: dify
data:
  REDIS_PORT: '6379'
  CELERY_BROKER_URL: 'redis://$(REDIS_USERNAME):$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/1'
  ...
# Dify Worker Server Start
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dify-worker
  namespace: dify
  labels:
    app: dify-worker
    app.kubernetes.io/instance: dify-worker
spec:
  serviceName: "dify-worker"
  replicas: 1
  selector:
    matchLabels:
      app: dify-worker
  template:
    metadata:
      labels:
        app: dify-worker
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: dify-api-storage
        hostPath:
          path: /root/dify/app/api/storage
          type: DirectoryOrCreate
      containers:
      - name: dify-worker
        image: langgenius/dify-api:1.3.0
        ports:
        - containerPort: 5001
          protocol: TCP
        envFrom:
        - configMapRef:
            name: dify-shared-config
        env:
        # - name: CONSOLE_WEB_URL
        #   value: ""
        - name: MODE
          value: worker

        - name: CELERY_BROKER_URL
          value: >-
              redis://$(REDIS_USERNAME):$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/1
```
